[package]
name = "rio_turtle"
version = "0.4.2"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "Apache-2.0"
readme = "../README.md"
keywords = ["RDF", "Turtle", "TriG", "N-Triples", "N-Quads"]
repository = "https://github.com/Tpt/rio"
description = """
RDF Turtle, Trig, N-Triples and N-Quads parsers and serializers
"""
edition = "2018"

[dependencies]
rio_api = "0.4"

[features]
default = []
generalized = ["rio_api/generalized"]