[package]
name = "rio_xml"
version = "0.4.2"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "Apache-2.0"
readme = "../README.md"
keywords = ["RDF", "XML", "parser"]
repository = "https://github.com/Tpt/rio"
description = """
RDF/XML parser and serializer
"""
edition = "2018"

[dependencies]
rio_api = "0.4"
quick-xml = "0.18"
